"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";

export default function ImageLightbox({images,title}:{images:string[];title:string}){
  const[index,setIndex]=useState<number|null>(null);
  useEffect(()=>{if(index===null)return;const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setIndex(null);if(event.key==="ArrowLeft")setIndex(current=>current===null?null:(current-1+images.length)%images.length);if(event.key==="ArrowRight")setIndex(current=>current===null?null:(current+1)%images.length)};document.body.style.overflow="hidden";addEventListener("keydown",key);return()=>{document.body.style.overflow="";removeEventListener("keydown",key)}},[index,images.length]);
  return <><div className="space-y-5">{images.map((image,i)=><button type="button" key={`${image}-${i}`} onClick={()=>setIndex(i)} className="block w-full cursor-zoom-in rounded-3xl bg-transparent p-0" aria-label={`查看第 ${i+1} 张大图`}><img src={image} alt={`${title} 第 ${i+1} 张`} className="mx-auto max-h-[82vh] max-w-full rounded-2xl object-contain"/><span className="mt-2 block text-center text-xs text-stone-500">点击查看大图 · {i+1}/{images.length}</span></button>)}</div>{index!==null&&<div role="dialog" aria-modal="true" aria-label="图片查看器" onClick={()=>setIndex(null)} className="fixed inset-0 z-[100] grid place-items-center bg-black/90 p-3 sm:p-8"><button onClick={()=>setIndex(null)} aria-label="关闭大图" className="absolute right-4 top-4 z-10 grid size-11 place-items-center rounded-full bg-white/15 text-3xl text-white hover:bg-white/25">×</button><div className="absolute left-1/2 top-5 -translate-x-1/2 rounded-full bg-black/50 px-4 py-2 text-sm text-white">第 {index+1} 张 / 共 {images.length} 张</div>{images.length>1&&<button onClick={event=>{event.stopPropagation();setIndex((index-1+images.length)%images.length)}} aria-label="上一张" className="absolute left-3 z-10 grid size-12 place-items-center rounded-full bg-white/15 text-4xl text-white hover:bg-white/25 sm:left-8">‹</button>}<img onClick={event=>event.stopPropagation()} src={images[index]} alt={`${title} 第 ${index+1} 张大图`} className="max-h-[90vh] max-w-[94vw] select-none object-contain"/>{images.length>1&&<button onClick={event=>{event.stopPropagation();setIndex((index+1)%images.length)}} aria-label="下一张" className="absolute right-3 z-10 grid size-12 place-items-center rounded-full bg-white/15 text-4xl text-white hover:bg-white/25 sm:right-8">›</button>}</div>}</>
}
