import { NextRequest,NextResponse } from "next/server";
import { and,eq } from "drizzle-orm";
import { artworks,profiles,verificationApplications,users } from "@/db/schema";
import { getDb } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { encryptPersonal } from "@/lib/crypto";
import { userApiError } from "@/lib/api-error";
import { getArtworkAllUrls } from "@/lib/image";
function objectName(url:string){const raw=url.split("/").pop()?.split("?")[0]||"";try{return decodeURIComponent(raw)}catch{return raw}}
export async function POST(request:NextRequest){try{const auth=await requireUser(request),raw:unknown=await request.json(),body=raw&&typeof raw==="object"?raw as Record<string,unknown>:{},representativeImages:string[]=[...new Set((Array.isArray(body.representativeImages)?body.representativeImages:[]).map(String).filter(Boolean))],db=await getDb(),[user]=await db.select().from(users).where(eq(users.id,auth.userId));if(!user||user.role!=="artist")return NextResponse.json({error:"只有画师账号可以申请认证"},{status:403});if(representativeImages.length<3||representativeImages.length>5)return NextResponse.json({error:"请选择 3–5 张代表图"},{status:400});if(body.originalityPromise!==true)return NextResponse.json({error:"请确认手画原创或合法授权承诺"},{status:400});if((await db.select({id:verificationApplications.id}).from(verificationApplications).where(and(eq(verificationApplications.userId,auth.userId),eq(verificationApplications.status,0)))).length)return NextResponse.json({error:"你的认证申请正在审核中，请勿重复提交"},{status:409});const approved=await db.select().from(artworks).where(and(eq(artworks.userId,auth.userId),eq(artworks.status,1))),allowed=new Set<string>(approved.flatMap(work=>getArtworkAllUrls(work)).map(objectName));if(representativeImages.some(url=>!allowed.has(objectName(url))))return NextResponse.json({error:"只能选择当前账号已审核通过的作品图片"},{status:400});const realName=String(body.realName||"").trim().slice(0,50);await db.transaction(async tx=>{await tx.insert(profiles).values({userId:user.id,displayName:user.displayName,profileStatus:0}).onConflictDoUpdate({target:profiles.userId,set:{displayName:user.displayName,profileStatus:0,updatedAt:new Date()}});await tx.insert(verificationApplications).values({userId:auth.userId,realName:realName?encryptPersonal(realName):null,representativeImages:JSON.stringify(representativeImages)});await tx.update(users).set({verificationRequestedAt:new Date()}).where(eq(users.id,auth.userId))});return NextResponse.json({ok:true,message:"认证申请已提交，等待站长审核"})}catch(error){return userApiError(error,"verification-application","登录已过期，请重新登录")}}
