"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { useState } from "react";
import { getArtworkThumbnail } from "@/lib/image";

export type Work={id:number;title:string;imageUrl:string;thumbnailUrl?:string|null;displayUrl?:string|null;originalUrl?:string|null;images?:string;imageVariants?:string;tags:string;status:number};
async function readJson(response:Response){const text=await response.text();try{return text?JSON.parse(text):{}}catch{return{error:"服务器响应异常"}}}
export default function ArtworkList({works}:{works:Work[]}){const[items,setItems]=useState(works),[busy,setBusy]=useState<number|null>(null),[message,setMessage]=useState("");async function remove(work:Work){const verb=work.status===0?"撤回审核":"删除";if(!confirm(`确定${verb}《${work.title}》吗？作品记录和全部图片将永久删除。`))return;setBusy(work.id);const token=localStorage.getItem("palette_token")||"";try{const response=await fetch(`/api/artworks/${work.id}/manage`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}}),result=await readJson(response);if(!response.ok)throw new Error(result.error||`${verb}失败`);setItems(current=>current.filter(item=>item.id!==work.id));setMessage(result.message||`${verb}成功`)}catch(error){setMessage(error instanceof Error?error.message:`${verb}失败`)}finally{setBusy(null)}}return <>{message&&<p aria-live="polite" className="mb-4 rounded-xl bg-orange-50 p-3 text-sm text-orange-800">{message}</p>}<div className="grid gap-5 sm:grid-cols-3">{items.map(work=><article key={work.id} className="overflow-hidden rounded-3xl bg-white"><Link href={`/artwork/${work.id}`}><img src={getArtworkThumbnail(work)} className="aspect-square w-full object-cover" alt={work.title}/></Link><div className="p-4"><b>{work.title}</b><p className="text-sm text-stone-500">{work.status===1?"公开":work.status===2?"下架":"待审核"}</p><button disabled={busy!==null} onClick={()=>remove(work)} className="mt-3 rounded-full border border-red-200 px-4 py-2 text-sm text-red-600 disabled:opacity-50">{busy===work.id?"正在清理…":work.status===0?"撤回审核并清理图片":"删除作品和图片"}</button></div></article>)}</div></>}
