"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useRef, useState } from "react";
import UploadStatus from "@/components/UploadStatus";

type Uploaded = { urls:string[];displayUrls:string[];originalUrls:string[];variants:unknown[];hashes:string[];uploadTicket:string };
async function readJson(response:Response){const text=await response.text();try{return text?JSON.parse(text):{}}catch{return{error:"服务器响应异常，请稍后重试"}}}

export default function ArtworkCreatePanel({onCreated}:{onCreated:()=>void}){
  const input=useRef<HTMLInputElement>(null),[open,setOpen]=useState(false),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[tags,setTags]=useState(""),[agreed,setAgreed]=useState(false),[dragging,setDragging]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>()=>{previews.forEach(URL.revokeObjectURL)},[previews]);
  function add(next:File[]){setMessage("");const room=10-files.length,valid=next.filter(file=>/image\/(jpeg|png|webp)/.test(file.type)&&file.size<=10_485_760).slice(0,room);const invalid=next.length-valid.length;if(valid.length){setFiles(current=>[...current,...valid]);setPreviews(current=>[...current,...valid.map(URL.createObjectURL)])}if(invalid)setMessage("仅支持 10MB 以内的 JPG、PNG、WebP，单件作品最多 10 张图片");if(input.current)input.current.value=""}
  function remove(index:number){URL.revokeObjectURL(previews[index]);setFiles(current=>current.filter((_,i)=>i!==index));setPreviews(current=>current.filter((_,i)=>i!==index))}
  function reset(){previews.forEach(URL.revokeObjectURL);setFiles([]);setPreviews([]);setTitle("");setDescription("");setTags("");setAgreed(false)}
  async function submit(event:React.FormEvent){event.preventDefault();if(!files.length)return setMessage("请先选择至少一张作品图片");if(!title.trim())return setMessage("请填写作品标题");if(!agreed)return setMessage("请先同意用户协议和社区规范");setBusy(true);setMessage("正在处理和上传图片，请不要关闭页面…");const uploadedTickets:string[]=[];const token=localStorage.getItem("palette_token")||"";try{const all:Uploaded[]=[];for(let index=0;index<files.length;index++){setMessage(`正在上传第 ${index+1}/${files.length} 张图片…`);const form=new FormData();form.append("images",files[index]);const uploadResponse=await fetch("/api/upload",{method:"POST",headers:{authorization:`Bearer ${token}`},body:form});const uploaded=await readJson(uploadResponse) as Uploaded&{error?:string};if(!uploadResponse.ok)throw new Error(uploaded.error||`第 ${index+1} 张图片上传失败`);all.push(uploaded);uploadedTickets.push(uploaded.uploadTicket)}setMessage("图片上传完成，正在提交作品…");const uploaded={urls:all.flatMap(x=>x.urls),displayUrls:all.flatMap(x=>x.displayUrls),originalUrls:all.flatMap(x=>x.originalUrls),variants:all.flatMap(x=>x.variants),hashes:all.flatMap(x=>x.hashes),uploadTickets:all.map(x=>x.uploadTicket)};const response=await fetch("/api/artworks",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({title:title.trim(),description:description.trim(),tags:tags.trim(),images:uploaded.urls,displayUrls:uploaded.displayUrls,originalUrls:uploaded.originalUrls,variants:uploaded.variants,hashes:uploaded.hashes,uploadTickets:uploaded.uploadTickets,agreed:true})}),result=await readJson(response);if(!response.ok){await fetch("/api/upload/cleanup",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({uploadTickets:uploaded.uploadTickets})}).catch(()=>undefined);throw new Error(result.error||"作品提交失败")}setMessage(result.message||"作品已提交");reset();setOpen(false);onCreated()}catch(error){if(uploadedTickets.length)await fetch("/api/upload/cleanup",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({uploadTickets:uploadedTickets})}).catch(()=>undefined);setMessage(error instanceof Error?error.message:"上传失败，请稍后重试")}finally{setBusy(false)}}
  return <section className="rounded-3xl bg-white p-5 shadow-sm sm:p-7 dark:bg-[#1a1a1a]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">发布新作品</h2><p className="mt-1 text-sm text-stone-500">手机点选图片，电脑也可以拖拽；单件作品最多 10 张。</p></div><button type="button" onClick={()=>setOpen(!open)} className="btn min-h-11">{open?"收起":"＋ 添加作品"}</button></div>{open&&<form onSubmit={submit} className="mt-6 space-y-4"><input ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={event=>add(Array.from(event.target.files||[]))}/><div onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy"}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);add(Array.from(event.dataTransfer.files))}} className={`rounded-2xl border-2 border-dashed p-6 text-center transition sm:p-10 ${dragging?"border-orange-500 bg-orange-50":"border-stone-300"}`}><button type="button" onClick={()=>input.current?.click()} className="btn min-h-12">选择作品图片</button><p className="mt-3 text-sm text-stone-500">或把图片拖到这里 · JPG / PNG / WebP · 每张不超过 10MB</p></div>{previews.length>0&&<div><div className="mb-2 flex justify-between text-sm"><b>已选择 {files.length}/10 张</b><button type="button" onClick={reset} className="text-red-600">清空</button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{previews.map((src,index)=><div key={src} className="relative overflow-hidden rounded-2xl border"><img src={src} className="aspect-square w-full object-cover" alt={`待上传图片 ${index+1}`}/><button type="button" aria-label="移除图片" onClick={()=>remove(index)} className="absolute right-2 top-2 grid size-9 place-items-center rounded-full bg-black/70 text-xl text-white">×</button><span className="absolute bottom-2 left-2 rounded-full bg-black/60 px-2 py-1 text-xs text-white">{index+1}</span></div>)}</div></div>}<label className="block text-sm">作品标题<input required maxLength={100} className="input mt-2" value={title} onChange={event=>setTitle(event.target.value)} placeholder="给作品起个名字"/></label><label className="block text-sm">作品简介（选填）<textarea maxLength={1000} className="input mt-2 min-h-28" value={description} onChange={event=>setDescription(event.target.value)} placeholder="介绍创作灵感、媒介或过程"/></label><label className="block text-sm">标签（选填）<input className="input mt-2" value={tags} onChange={event=>setTags(event.target.value)} placeholder="例如：水彩 风景 原创"/></label><label className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={agreed} onChange={event=>setAgreed(event.target.checked)}/><span>我确认作品为本人原创或已获合法授权，并同意《用户协议》和《社区规范》。</span></label><UploadStatus message={message}/><button disabled={busy||!files.length||!agreed} className="btn min-h-12 w-full disabled:opacity-50">{busy?"正在上传，请稍候…":"提交作品"}</button></form>}</section>}
