"use client";
/* eslint-disable @next/next/no-img-element */
import { useMemo, useState } from "react";
import { getArtworkDisplays } from "@/lib/image";
type Work={id:number;title:string;imageUrl:string;thumbnailUrl?:string|null;displayUrl?:string|null;originalUrl?:string|null;images?:string;imageVariants?:string;tags:string;status:number};

type Props={works:Work[];pending:boolean;verified:boolean;onSubmitted:()=>void};
async function readJson(response:Response){const text=await response.text();try{return text?JSON.parse(text):{}}catch{return{error:"服务器响应异常，请稍后重试"}}}

export default function VerificationPanel({works,pending,verified,onSubmitted}:Props){
  const[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[realName,setRealName]=useState(""),[agreed,setAgreed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const choices=useMemo(()=>works.filter(work=>work.status===1).flatMap(work=>{const images=getArtworkDisplays(work);return images.map((url,index)=>({url,title:`${work.title}${images.length>1?` · 第 ${index+1} 张`:""}`}))}),[works]);
  function toggle(url:string){setMessage("");setSelected(current=>current.includes(url)?current.filter(item=>item!==url):current.length>=5?current:[...current,url])}
  async function submit(event:React.FormEvent){event.preventDefault();if(selected.length<3||selected.length>5)return setMessage("请选择 3–5 张代表图");if(!agreed)return setMessage("请先确认原创或合法授权承诺");setBusy(true);setMessage("正在提交认证申请，请稍候…");try{const token=localStorage.getItem("palette_token")||"",response=await fetch("/api/profile/verify",{method:"POST",cache:"no-store",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({representativeImages:selected,realName,originalityPromise:agreed})}),result=await readJson(response);if(!response.ok)return setMessage(result.error||"提交失败，请稍后重试");setMessage(result.message||"申请已提交，等待审核");onSubmitted()}catch{setMessage("网络连接失败，请检查网络后重试")}finally{setBusy(false)}}
  if(verified)return <div className="rounded-2xl bg-green-50 p-4 text-sm text-green-700">✓ 你已经通过画师认证</div>;
  if(pending)return <div className="rounded-2xl bg-orange-50 p-4 text-sm text-orange-700">认证申请正在审核中，审核结果会显示在账号中心。</div>;
  return <section className="rounded-3xl bg-white p-6 shadow-sm dark:bg-[#1a1a1a]"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">画师认证</h2><p className="mt-1 text-sm text-stone-500">从已经审核通过的作品中选择 3–5 张代表图。</p></div><button type="button" onClick={()=>setOpen(!open)} className="btn">{open?"收起申请":"开始申请"}</button></div>{open&&<form onSubmit={submit} className="mt-6 space-y-5">{choices.length>=3?<div><div className="mb-3 flex items-center justify-between"><b>选择代表图</b><span className={selected.length>=3?"text-green-600":"text-orange-600"}>已选 {selected.length}/5</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{choices.map(choice=><button key={choice.url} type="button" onClick={()=>toggle(choice.url)} className={`relative overflow-hidden rounded-2xl border-2 text-left ${selected.includes(choice.url)?"border-orange-500 ring-2 ring-orange-100":"border-transparent"}`}><img src={choice.url} alt={choice.title} className="aspect-square w-full object-cover"/><span className="block truncate p-2 text-sm">{choice.title}</span>{selected.includes(choice.url)&&<span className="absolute right-2 top-2 grid size-7 place-items-center rounded-full bg-orange-500 text-white">✓</span>}</button>)}</div></div>:<div className="rounded-2xl border border-dashed p-6 text-center text-sm text-stone-500">审核通过的作品图片不足 3 张，请先发布作品并等待作品审核通过。</div>}<label className="block text-sm">真实姓名（选填，仅用于认证审核，不公开）<input className="input mt-2" value={realName} onChange={event=>setRealName(event.target.value)} maxLength={50}/></label><label className="flex gap-3 rounded-2xl border p-4 text-sm"><input type="checkbox" checked={agreed} onChange={event=>setAgreed(event.target.checked)}/><span>我确认所选作品为本人手画原创，或已获得合法授权，并愿意对提交内容负责。</span></label>{message&&<p aria-live="polite" className="rounded-xl bg-orange-50 p-3 text-sm text-orange-700">{message}</p>}<button disabled={busy||choices.length<3||selected.length<3||!agreed} className="btn w-full disabled:opacity-50">{busy?"正在处理…":selected.length<3?`还需选择 ${3-selected.length} 张代表图`:"提交认证申请"}</button></form>}</section>
}
